### ISSUE TITLE
Better plugin description

### ISSUE THREAD

**Issue by ryanneve** [lsellens/octoprint-manual_bed_tramming#17]
Just a small thing, but from the current description it's not entirely clear what this plugin does.  Perhaps replace:
## This plugins adds leveling controls for your CR-10 to the Control tab.
with something like:
## This plugin adds buttons which with one click position the print head over a corner leveling screw or the center of the print area.

My first thought was it had something to do with auto or mesh leveling.

**Comment by bcsteeve** [comment]
Just to provide a counter-view...  your presumption that it has to do with auto or mesh leveling is your error in reading what isn't there, rather than misunderstanding what is there.  The description makes no mention of either auto or mesh or really says anything to suggest it could have anything to do with either.  (In fact, auto/mesh leveling systems have nothing to do with leveling... but that's a different discussion).

However, there's also no harm in being more specific about the description and I agree with ryanneve's wording, with a slight change (drop "one click" or move it to the end of sentence) for readability sake:

## This plugin adds buttons which position the print head over a corner leveling screw, or the center of the print area [, with one click]

**Comment by ryanneve** [comment]
Bcsteeve's suggestion looks great to me.

**Comment by electr0sheep** [comment]
I updated the plugin repo. If you guys get a chance, let me know what you think.

**Comment by ryanneve** [comment]
The README.md still just says "This plugins adds leveling controls for your CR-10 to the Control tab."
Perhaps I'm looking in the wrong place?

**Comment by electr0sheep** [comment]
@ryanneve Oh, I thought you were talking about the description in the official plugin repo. I updated readme.md after realizing I was mistaken about what you meant.

**Comment by ryanneve** [comment]
Thanks!
